packages:
  - .

engineStrict: true
strictPeerDependencies: true
autoInstallPeers: false
resolutionMode: highest
nodeLinker: hoisted
minimumReleaseAge: 1440
blockExoticSubdeps: true
strictDepBuilds: true
allowBuilds:
  esbuild: true
